### PR TITLE
feat: export the prepareSubmissionDoc function for kazana-email-box

### PR DESCRIPTION
**Pull request by lucidNTR**

### CODE REVIEW

**Comment by gr2m** [comment]
I don't think it's a good idea to extend the kazana configuration with `prepareSubmissionDoc` only for this one case. There should be a better way to share the method with another module. For now I would simply do `var repareSubmissionDoc = require('kazana-raw-data/lib/utils/prepare-submission-doc')` and an issue to find a better solution for this.

We plan to create a client API for `kazana-raw-data` which could be exposed at `kazana-raw-data/api`. That will resolve that issue, too, because other modules would use the exposed JS API instead of sending own requests

**Comment by lucidNTR** [comment]
@gr2m the reasoning was to at least make explicit inside the raw-data that the funcition is used outside and change of it can break another module. but i can also just do it with var repareSubmissionDoc = require('kazana-raw-data/lib/utils/prepare-submission-doc')

**Comment by gr2m** [comment]
I'd keep the configuration that kazana apps / modules export as minimal as possible, so I'd do `var repareSubmissionDoc = require('kazana-raw-data/lib/utils/prepare-submission-doc')`, but only as a temporary workaround, hence the issue to remind us to fix that

**Comment by lucidNTR** [comment]
ok great

**Comment by gr2m** [comment]
here's the issue about exposing an AIP https://github.com/eHealthAfrica/kazana-raw-data/issues/7

**Pull request closed without merging**
